//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoCuentaFinanciera complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoCuentaFinanciera">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TipoCodigoCuenta" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="CodigoMoneda" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="NotaPago" type="{http://www.growupit.com/gideEsquema}TipoTexto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SucursualInstitucionFinanciera" type="{http://www.growupit.com/gideEsquema}TipoSucursal" minOccurs="0"/>
 *         &lt;element name="Pais" type="{http://www.growupit.com/gideEsquema}TipoPais" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoCuentaFinanciera", propOrder = {
    "id",
    "nombre",
    "tipoCodigoCuenta",
    "codigoMoneda",
    "notaPago",
    "sucursualInstitucionFinanciera",
    "pais"
})
public class TipoCuentaFinanciera
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID")
    protected TipoIdentificador id;
    @XmlElement(name = "Nombre")
    protected String nombre;
    @XmlElement(name = "TipoCodigoCuenta")
    protected TipoCodigo tipoCodigoCuenta;
    @XmlElement(name = "CodigoMoneda")
    protected TipoCodigo codigoMoneda;
    @XmlElement(name = "NotaPago")
    protected List<TipoTexto> notaPago;
    @XmlElement(name = "SucursualInstitucionFinanciera")
    protected TipoSucursal sucursualInstitucionFinanciera;
    @XmlElement(name = "Pais")
    protected TipoPais pais;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the tipoCodigoCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getTipoCodigoCuenta() {
        return tipoCodigoCuenta;
    }

    /**
     * Sets the value of the tipoCodigoCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setTipoCodigoCuenta(TipoCodigo value) {
        this.tipoCodigoCuenta = value;
    }

    /**
     * Gets the value of the codigoMoneda property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoMoneda() {
        return codigoMoneda;
    }

    /**
     * Sets the value of the codigoMoneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoMoneda(TipoCodigo value) {
        this.codigoMoneda = value;
    }

    /**
     * Gets the value of the notaPago property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notaPago property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotaPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTexto }
     * 
     * 
     */
    public List<TipoTexto> getNotaPago() {
        if (notaPago == null) {
            notaPago = new ArrayList<TipoTexto>();
        }
        return this.notaPago;
    }

    /**
     * Gets the value of the sucursualInstitucionFinanciera property.
     * 
     * @return
     *     possible object is
     *     {@link TipoSucursal }
     *     
     */
    public TipoSucursal getSucursualInstitucionFinanciera() {
        return sucursualInstitucionFinanciera;
    }

    /**
     * Sets the value of the sucursualInstitucionFinanciera property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoSucursal }
     *     
     */
    public void setSucursualInstitucionFinanciera(TipoSucursal value) {
        this.sucursualInstitucionFinanciera = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPais }
     *     
     */
    public TipoPais getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPais }
     *     
     */
    public void setPais(TipoPais value) {
        this.pais = value;
    }

}
