//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoListaPrecios complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoListaPrecios">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="CodigoEstado" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="PeridoValidez" type="{http://www.growupit.com/gideEsquema}TipoPeriodo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ListaPreciosPrevia" type="{http://www.growupit.com/gideEsquema}TipoListaPrecios" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoListaPrecios", propOrder = {
    "id",
    "codigoEstado",
    "peridoValidez",
    "listaPreciosPrevia"
})
public class TipoListaPrecios
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID")
    protected TipoIdentificador id;
    @XmlElement(name = "CodigoEstado")
    protected TipoCodigo codigoEstado;
    @XmlElement(name = "PeridoValidez")
    protected List<TipoPeriodo> peridoValidez;
    @XmlElement(name = "ListaPreciosPrevia")
    protected TipoListaPrecios listaPreciosPrevia;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the codigoEstado property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoEstado() {
        return codigoEstado;
    }

    /**
     * Sets the value of the codigoEstado property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoEstado(TipoCodigo value) {
        this.codigoEstado = value;
    }

    /**
     * Gets the value of the peridoValidez property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the peridoValidez property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeridoValidez().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoPeriodo }
     * 
     * 
     */
    public List<TipoPeriodo> getPeridoValidez() {
        if (peridoValidez == null) {
            peridoValidez = new ArrayList<TipoPeriodo>();
        }
        return this.peridoValidez;
    }

    /**
     * Gets the value of the listaPreciosPrevia property.
     * 
     * @return
     *     possible object is
     *     {@link TipoListaPrecios }
     *     
     */
    public TipoListaPrecios getListaPreciosPrevia() {
        return listaPreciosPrevia;
    }

    /**
     * Sets the value of the listaPreciosPrevia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoListaPrecios }
     *     
     */
    public void setListaPreciosPrevia(TipoListaPrecios value) {
        this.listaPreciosPrevia = value;
    }

}
