//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for TipoDatosDeControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoDatosDeControl">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Usuario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Contrasenia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumeroDocumentoElectronico" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TipoDocumentoElectronico" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TipoFactura" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FrechaFacturacion" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Prefijo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDatosDeControl", propOrder = {
    "usuario",
    "contrasenia",
    "numeroDocumentoElectronico",
    "tipoDocumentoElectronico",
    "tipoFactura",
    "frechaFacturacion",
    "prefijo"
})
public class TipoDatosDeControl
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "Usuario", required = true)
    protected String usuario;
    @XmlElement(name = "Contrasenia", required = true)
    protected String contrasenia;
    @XmlElement(name = "NumeroDocumentoElectronico")
    protected int numeroDocumentoElectronico;
    @XmlElement(name = "TipoDocumentoElectronico")
    protected int tipoDocumentoElectronico;
    @XmlElement(name = "TipoFactura")
    protected int tipoFactura;
    @XmlElement(name = "FrechaFacturacion", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar frechaFacturacion;
    @XmlElement(name = "Prefijo")
    protected String prefijo;

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

    /**
     * Gets the value of the contrasenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContrasenia() {
        return contrasenia;
    }

    /**
     * Sets the value of the contrasenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContrasenia(String value) {
        this.contrasenia = value;
    }

    /**
     * Gets the value of the numeroDocumentoElectronico property.
     * 
     */
    public int getNumeroDocumentoElectronico() {
        return numeroDocumentoElectronico;
    }

    /**
     * Sets the value of the numeroDocumentoElectronico property.
     * 
     */
    public void setNumeroDocumentoElectronico(int value) {
        this.numeroDocumentoElectronico = value;
    }

    /**
     * Gets the value of the tipoDocumentoElectronico property.
     * 
     */
    public int getTipoDocumentoElectronico() {
        return tipoDocumentoElectronico;
    }

    /**
     * Sets the value of the tipoDocumentoElectronico property.
     * 
     */
    public void setTipoDocumentoElectronico(int value) {
        this.tipoDocumentoElectronico = value;
    }

    /**
     * Gets the value of the tipoFactura property.
     * 
     */
    public int getTipoFactura() {
        return tipoFactura;
    }

    /**
     * Sets the value of the tipoFactura property.
     * 
     */
    public void setTipoFactura(int value) {
        this.tipoFactura = value;
    }

    /**
     * Gets the value of the frechaFacturacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getFrechaFacturacion() {
        return frechaFacturacion;
    }

    /**
     * Sets the value of the frechaFacturacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrechaFacturacion(Calendar value) {
        this.frechaFacturacion = value;
    }

    /**
     * Gets the value of the prefijo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefijo() {
        return prefijo;
    }

    /**
     * Sets the value of the prefijo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefijo(String value) {
        this.prefijo = value;
    }

}
