//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoSubtotalImpuesto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoSubtotalImpuesto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MontoGravable" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="MontoImpuesto" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="CalculoSecuenciaNumerica" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MontoImpuestoMonedaTransaccion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Porcentaje" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="BaseUnidadMedida" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MontoPorUnidad" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="NivelRango" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="PorcentajeNivelRango" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ImpuestoCategoria" type="{http://www.growupit.com/gideEsquema}TipoImpuestoCategoria"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoSubtotalImpuesto", propOrder = {
    "montoGravable",
    "montoImpuesto",
    "calculoSecuenciaNumerica",
    "montoImpuestoMonedaTransaccion",
    "porcentaje",
    "baseUnidadMedida",
    "montoPorUnidad",
    "nivelRango",
    "porcentajeNivelRango",
    "impuestoCategoria"
})
public class TipoSubtotalImpuesto
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "MontoGravable", required = true)
    protected BigDecimal montoGravable;
    @XmlElement(name = "MontoImpuesto", required = true)
    protected BigDecimal montoImpuesto;
    @XmlElement(name = "CalculoSecuenciaNumerica")
    protected BigDecimal calculoSecuenciaNumerica;
    @XmlElement(name = "MontoImpuestoMonedaTransaccion")
    protected BigDecimal montoImpuestoMonedaTransaccion;
    @XmlElement(name = "Porcentaje", required = true)
    protected BigDecimal porcentaje;
    @XmlElement(name = "BaseUnidadMedida")
    protected BigDecimal baseUnidadMedida;
    @XmlElement(name = "MontoPorUnidad")
    protected BigDecimal montoPorUnidad;
    @XmlElement(name = "NivelRango")
    protected TipoTexto nivelRango;
    @XmlElement(name = "PorcentajeNivelRango")
    protected BigDecimal porcentajeNivelRango;
    @XmlElement(name = "ImpuestoCategoria", required = true)
    protected TipoImpuestoCategoria impuestoCategoria;

    /**
     * Gets the value of the montoGravable property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoGravable() {
        return montoGravable;
    }

    /**
     * Sets the value of the montoGravable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoGravable(BigDecimal value) {
        this.montoGravable = value;
    }

    /**
     * Gets the value of the montoImpuesto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoImpuesto() {
        return montoImpuesto;
    }

    /**
     * Sets the value of the montoImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoImpuesto(BigDecimal value) {
        this.montoImpuesto = value;
    }

    /**
     * Gets the value of the calculoSecuenciaNumerica property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculoSecuenciaNumerica() {
        return calculoSecuenciaNumerica;
    }

    /**
     * Sets the value of the calculoSecuenciaNumerica property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalculoSecuenciaNumerica(BigDecimal value) {
        this.calculoSecuenciaNumerica = value;
    }

    /**
     * Gets the value of the montoImpuestoMonedaTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoImpuestoMonedaTransaccion() {
        return montoImpuestoMonedaTransaccion;
    }

    /**
     * Sets the value of the montoImpuestoMonedaTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoImpuestoMonedaTransaccion(BigDecimal value) {
        this.montoImpuestoMonedaTransaccion = value;
    }

    /**
     * Gets the value of the porcentaje property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcentaje() {
        return porcentaje;
    }

    /**
     * Sets the value of the porcentaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcentaje(BigDecimal value) {
        this.porcentaje = value;
    }

    /**
     * Gets the value of the baseUnidadMedida property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseUnidadMedida() {
        return baseUnidadMedida;
    }

    /**
     * Sets the value of the baseUnidadMedida property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseUnidadMedida(BigDecimal value) {
        this.baseUnidadMedida = value;
    }

    /**
     * Gets the value of the montoPorUnidad property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoPorUnidad() {
        return montoPorUnidad;
    }

    /**
     * Sets the value of the montoPorUnidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoPorUnidad(BigDecimal value) {
        this.montoPorUnidad = value;
    }

    /**
     * Gets the value of the nivelRango property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getNivelRango() {
        return nivelRango;
    }

    /**
     * Sets the value of the nivelRango property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setNivelRango(TipoTexto value) {
        this.nivelRango = value;
    }

    /**
     * Gets the value of the porcentajeNivelRango property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorcentajeNivelRango() {
        return porcentajeNivelRango;
    }

    /**
     * Sets the value of the porcentajeNivelRango property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorcentajeNivelRango(BigDecimal value) {
        this.porcentajeNivelRango = value;
    }

    /**
     * Gets the value of the impuestoCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link TipoImpuestoCategoria }
     *     
     */
    public TipoImpuestoCategoria getImpuestoCategoria() {
        return impuestoCategoria;
    }

    /**
     * Sets the value of the impuestoCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoImpuestoCategoria }
     *     
     */
    public void setImpuestoCategoria(TipoImpuestoCategoria value) {
        this.impuestoCategoria = value;
    }

}
