//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AgenciaExtensionId" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="NombreAgenciaExtension" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="VersionExtensionId" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="AgenciaExtensionURI" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="ExtensionURI" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="CodigoRazonExtension" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="ContenidoExtension" type="{http://www.growupit.com/gideEsquema}TipoContenidoExtension"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoExtension", propOrder = {
    "id",
    "nombre",
    "agenciaExtensionId",
    "nombreAgenciaExtension",
    "versionExtensionId",
    "agenciaExtensionURI",
    "extensionURI",
    "codigoRazonExtension",
    "extension",
    "contenidoExtension"
})
public class TipoExtension
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID")
    protected TipoIdentificador id;
    @XmlElement(name = "Nombre")
    protected String nombre;
    @XmlElement(name = "AgenciaExtensionId")
    protected TipoIdentificador agenciaExtensionId;
    @XmlElement(name = "NombreAgenciaExtension")
    protected TipoTexto nombreAgenciaExtension;
    @XmlElement(name = "VersionExtensionId")
    protected TipoIdentificador versionExtensionId;
    @XmlElement(name = "AgenciaExtensionURI")
    protected TipoIdentificador agenciaExtensionURI;
    @XmlElement(name = "ExtensionURI")
    protected TipoIdentificador extensionURI;
    @XmlElement(name = "CodigoRazonExtension")
    protected TipoCodigo codigoRazonExtension;
    @XmlElement(name = "Extension")
    protected TipoTexto extension;
    @XmlElement(name = "ContenidoExtension", required = true)
    protected TipoContenidoExtension contenidoExtension;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the agenciaExtensionId property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getAgenciaExtensionId() {
        return agenciaExtensionId;
    }

    /**
     * Sets the value of the agenciaExtensionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setAgenciaExtensionId(TipoIdentificador value) {
        this.agenciaExtensionId = value;
    }

    /**
     * Gets the value of the nombreAgenciaExtension property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getNombreAgenciaExtension() {
        return nombreAgenciaExtension;
    }

    /**
     * Sets the value of the nombreAgenciaExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setNombreAgenciaExtension(TipoTexto value) {
        this.nombreAgenciaExtension = value;
    }

    /**
     * Gets the value of the versionExtensionId property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getVersionExtensionId() {
        return versionExtensionId;
    }

    /**
     * Sets the value of the versionExtensionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setVersionExtensionId(TipoIdentificador value) {
        this.versionExtensionId = value;
    }

    /**
     * Gets the value of the agenciaExtensionURI property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getAgenciaExtensionURI() {
        return agenciaExtensionURI;
    }

    /**
     * Sets the value of the agenciaExtensionURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setAgenciaExtensionURI(TipoIdentificador value) {
        this.agenciaExtensionURI = value;
    }

    /**
     * Gets the value of the extensionURI property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getExtensionURI() {
        return extensionURI;
    }

    /**
     * Sets the value of the extensionURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setExtensionURI(TipoIdentificador value) {
        this.extensionURI = value;
    }

    /**
     * Gets the value of the codigoRazonExtension property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoRazonExtension() {
        return codigoRazonExtension;
    }

    /**
     * Sets the value of the codigoRazonExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoRazonExtension(TipoCodigo value) {
        this.codigoRazonExtension = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setExtension(TipoTexto value) {
        this.extension = value;
    }

    /**
     * Gets the value of the contenidoExtension property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContenidoExtension }
     *     
     */
    public TipoContenidoExtension getContenidoExtension() {
        return contenidoExtension;
    }

    /**
     * Sets the value of the contenidoExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContenidoExtension }
     *     
     */
    public void setContenidoExtension(TipoContenidoExtension value) {
        this.contenidoExtension = value;
    }

}
