//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoTercero complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoTercero">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndicadorMarcaCuidado" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IndicadorMarcaAtencion" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SitioWebURI" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="ReferenciaLogotipoID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="PuntoFinalID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="IdentificacionTercero" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" maxOccurs="unbounded"/>
 *         &lt;element name="NombreTercero" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Idioma" type="{http://www.growupit.com/gideEsquema}TipoIdioma" minOccurs="0"/>
 *         &lt;element name="DireccionPostal" type="{http://www.growupit.com/gideEsquema}TipoDireccion" minOccurs="0"/>
 *         &lt;element name="Ubicacion" type="{http://www.growupit.com/gideEsquema}TipoUbicacion"/>
 *         &lt;element name="EsquemaImpuestosTercero" type="{http://www.growupit.com/gideEsquema}TipoEsquemaImpuestosTercero" maxOccurs="unbounded"/>
 *         &lt;element name="EntidadLegalTercero" type="{http://www.growupit.com/gideEsquema}TipoEntidadLegalTercero" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Contacto" type="{http://www.growupit.com/gideEsquema}TipoContacto" minOccurs="0"/>
 *         &lt;element name="Persona" type="{http://www.growupit.com/gideEsquema}TipoPersona" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TerceroAgencia" type="{http://www.growupit.com/gideEsquema}TipoTercero" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoTercero", propOrder = {
    "indicadorMarcaCuidado",
    "indicadorMarcaAtencion",
    "sitioWebURI",
    "referenciaLogotipoID",
    "puntoFinalID",
    "identificacionTercero",
    "nombreTercero",
    "idioma",
    "direccionPostal",
    "ubicacion",
    "esquemaImpuestosTercero",
    "entidadLegalTercero",
    "contacto",
    "persona",
    "terceroAgencia"
})
public class TipoTercero
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "IndicadorMarcaCuidado")
    protected Boolean indicadorMarcaCuidado;
    @XmlElement(name = "IndicadorMarcaAtencion")
    protected Boolean indicadorMarcaAtencion;
    @XmlElement(name = "SitioWebURI")
    protected TipoIdentificador sitioWebURI;
    @XmlElement(name = "ReferenciaLogotipoID")
    protected TipoIdentificador referenciaLogotipoID;
    @XmlElement(name = "PuntoFinalID")
    protected TipoIdentificador puntoFinalID;
    @XmlElement(name = "IdentificacionTercero", required = true)
    protected List<TipoIdentificador> identificacionTercero;
    @XmlElement(name = "NombreTercero")
    protected List<String> nombreTercero;
    @XmlElement(name = "Idioma")
    protected TipoIdioma idioma;
    @XmlElement(name = "DireccionPostal")
    protected TipoDireccion direccionPostal;
    @XmlElement(name = "Ubicacion", required = true)
    protected TipoUbicacion ubicacion;
    @XmlElement(name = "EsquemaImpuestosTercero", required = true)
    protected List<TipoEsquemaImpuestosTercero> esquemaImpuestosTercero;
    @XmlElement(name = "EntidadLegalTercero")
    protected List<TipoEntidadLegalTercero> entidadLegalTercero;
    @XmlElement(name = "Contacto")
    protected TipoContacto contacto;
    @XmlElement(name = "Persona")
    protected List<TipoPersona> persona;
    @XmlElement(name = "TerceroAgencia")
    protected TipoTercero terceroAgencia;

    /**
     * Gets the value of the indicadorMarcaCuidado property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorMarcaCuidado() {
        return indicadorMarcaCuidado;
    }

    /**
     * Sets the value of the indicadorMarcaCuidado property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorMarcaCuidado(Boolean value) {
        this.indicadorMarcaCuidado = value;
    }

    /**
     * Gets the value of the indicadorMarcaAtencion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorMarcaAtencion() {
        return indicadorMarcaAtencion;
    }

    /**
     * Sets the value of the indicadorMarcaAtencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorMarcaAtencion(Boolean value) {
        this.indicadorMarcaAtencion = value;
    }

    /**
     * Gets the value of the sitioWebURI property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getSitioWebURI() {
        return sitioWebURI;
    }

    /**
     * Sets the value of the sitioWebURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setSitioWebURI(TipoIdentificador value) {
        this.sitioWebURI = value;
    }

    /**
     * Gets the value of the referenciaLogotipoID property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getReferenciaLogotipoID() {
        return referenciaLogotipoID;
    }

    /**
     * Sets the value of the referenciaLogotipoID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setReferenciaLogotipoID(TipoIdentificador value) {
        this.referenciaLogotipoID = value;
    }

    /**
     * Gets the value of the puntoFinalID property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getPuntoFinalID() {
        return puntoFinalID;
    }

    /**
     * Sets the value of the puntoFinalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setPuntoFinalID(TipoIdentificador value) {
        this.puntoFinalID = value;
    }

    /**
     * Gets the value of the identificacionTercero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificacionTercero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacionTercero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoIdentificador }
     * 
     * 
     */
    public List<TipoIdentificador> getIdentificacionTercero() {
        if (identificacionTercero == null) {
            identificacionTercero = new ArrayList<TipoIdentificador>();
        }
        return this.identificacionTercero;
    }

    /**
     * Gets the value of the nombreTercero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nombreTercero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNombreTercero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNombreTercero() {
        if (nombreTercero == null) {
            nombreTercero = new ArrayList<String>();
        }
        return this.nombreTercero;
    }

    /**
     * Gets the value of the idioma property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdioma }
     *     
     */
    public TipoIdioma getIdioma() {
        return idioma;
    }

    /**
     * Sets the value of the idioma property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdioma }
     *     
     */
    public void setIdioma(TipoIdioma value) {
        this.idioma = value;
    }

    /**
     * Gets the value of the direccionPostal property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDireccion }
     *     
     */
    public TipoDireccion getDireccionPostal() {
        return direccionPostal;
    }

    /**
     * Sets the value of the direccionPostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDireccion }
     *     
     */
    public void setDireccionPostal(TipoDireccion value) {
        this.direccionPostal = value;
    }

    /**
     * Gets the value of the ubicacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoUbicacion }
     *     
     */
    public TipoUbicacion getUbicacion() {
        return ubicacion;
    }

    /**
     * Sets the value of the ubicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoUbicacion }
     *     
     */
    public void setUbicacion(TipoUbicacion value) {
        this.ubicacion = value;
    }

    /**
     * Gets the value of the esquemaImpuestosTercero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the esquemaImpuestosTercero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEsquemaImpuestosTercero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoEsquemaImpuestosTercero }
     * 
     * 
     */
    public List<TipoEsquemaImpuestosTercero> getEsquemaImpuestosTercero() {
        if (esquemaImpuestosTercero == null) {
            esquemaImpuestosTercero = new ArrayList<TipoEsquemaImpuestosTercero>();
        }
        return this.esquemaImpuestosTercero;
    }

    /**
     * Gets the value of the entidadLegalTercero property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entidadLegalTercero property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntidadLegalTercero().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoEntidadLegalTercero }
     * 
     * 
     */
    public List<TipoEntidadLegalTercero> getEntidadLegalTercero() {
        if (entidadLegalTercero == null) {
            entidadLegalTercero = new ArrayList<TipoEntidadLegalTercero>();
        }
        return this.entidadLegalTercero;
    }

    /**
     * Gets the value of the contacto property.
     * 
     * @return
     *     possible object is
     *     {@link TipoContacto }
     *     
     */
    public TipoContacto getContacto() {
        return contacto;
    }

    /**
     * Sets the value of the contacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoContacto }
     *     
     */
    public void setContacto(TipoContacto value) {
        this.contacto = value;
    }

    /**
     * Gets the value of the persona property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the persona property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersona().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoPersona }
     * 
     * 
     */
    public List<TipoPersona> getPersona() {
        if (persona == null) {
            persona = new ArrayList<TipoPersona>();
        }
        return this.persona;
    }

    /**
     * Gets the value of the terceroAgencia property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTercero }
     *     
     */
    public TipoTercero getTerceroAgencia() {
        return terceroAgencia;
    }

    /**
     * Sets the value of the terceroAgencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTercero }
     *     
     */
    public void setTerceroAgencia(TipoTercero value) {
        this.terceroAgencia = value;
    }

}
