//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoCoordenadasUbicacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoCoordenadasUbicacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CodigoSistemaCoordenadas" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="MedidaGradosLatitud" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MedidaMinutosLatitud" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CodigoDireccionLatitud" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="MedidaLongitudGrados" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="MedidaLongitudMinutos" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="CodigoLongitudDireccion" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoCoordenadasUbicacion", propOrder = {
    "codigoSistemaCoordenadas",
    "medidaGradosLatitud",
    "medidaMinutosLatitud",
    "codigoDireccionLatitud",
    "medidaLongitudGrados",
    "medidaLongitudMinutos",
    "codigoLongitudDireccion"
})
public class TipoCoordenadasUbicacion
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "CodigoSistemaCoordenadas")
    protected TipoCodigo codigoSistemaCoordenadas;
    @XmlElement(name = "MedidaGradosLatitud")
    protected BigDecimal medidaGradosLatitud;
    @XmlElement(name = "MedidaMinutosLatitud")
    protected BigDecimal medidaMinutosLatitud;
    @XmlElement(name = "CodigoDireccionLatitud")
    protected TipoCodigo codigoDireccionLatitud;
    @XmlElement(name = "MedidaLongitudGrados")
    protected BigDecimal medidaLongitudGrados;
    @XmlElement(name = "MedidaLongitudMinutos")
    protected BigDecimal medidaLongitudMinutos;
    @XmlElement(name = "CodigoLongitudDireccion")
    protected TipoCodigo codigoLongitudDireccion;

    /**
     * Gets the value of the codigoSistemaCoordenadas property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoSistemaCoordenadas() {
        return codigoSistemaCoordenadas;
    }

    /**
     * Sets the value of the codigoSistemaCoordenadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoSistemaCoordenadas(TipoCodigo value) {
        this.codigoSistemaCoordenadas = value;
    }

    /**
     * Gets the value of the medidaGradosLatitud property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedidaGradosLatitud() {
        return medidaGradosLatitud;
    }

    /**
     * Sets the value of the medidaGradosLatitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedidaGradosLatitud(BigDecimal value) {
        this.medidaGradosLatitud = value;
    }

    /**
     * Gets the value of the medidaMinutosLatitud property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedidaMinutosLatitud() {
        return medidaMinutosLatitud;
    }

    /**
     * Sets the value of the medidaMinutosLatitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedidaMinutosLatitud(BigDecimal value) {
        this.medidaMinutosLatitud = value;
    }

    /**
     * Gets the value of the codigoDireccionLatitud property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoDireccionLatitud() {
        return codigoDireccionLatitud;
    }

    /**
     * Sets the value of the codigoDireccionLatitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoDireccionLatitud(TipoCodigo value) {
        this.codigoDireccionLatitud = value;
    }

    /**
     * Gets the value of the medidaLongitudGrados property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedidaLongitudGrados() {
        return medidaLongitudGrados;
    }

    /**
     * Sets the value of the medidaLongitudGrados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedidaLongitudGrados(BigDecimal value) {
        this.medidaLongitudGrados = value;
    }

    /**
     * Gets the value of the medidaLongitudMinutos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedidaLongitudMinutos() {
        return medidaLongitudMinutos;
    }

    /**
     * Sets the value of the medidaLongitudMinutos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedidaLongitudMinutos(BigDecimal value) {
        this.medidaLongitudMinutos = value;
    }

    /**
     * Gets the value of the codigoLongitudDireccion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoLongitudDireccion() {
        return codigoLongitudDireccion;
    }

    /**
     * Sets the value of the codigoLongitudDireccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoLongitudDireccion(TipoCodigo value) {
        this.codigoLongitudDireccion = value;
    }

}
