//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter2;
import org.w3._2001.xmlschema.Adapter3;


/**
 * <p>Java class for TipoContrato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoContrato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="FechaEmision" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="HoraEmision" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="TipoCodigoContrato" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="TipoContrato" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="PeriodoValidez" type="{http://www.growupit.com/gideEsquema}TipoPeriodo" minOccurs="0"/>
 *         &lt;element name="CocumentoReferenciaContrato" type="{http://www.growupit.com/gideEsquema}TipoDocumentoReferencia" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoContrato", propOrder = {
    "id",
    "fechaEmision",
    "horaEmision",
    "tipoCodigoContrato",
    "tipoContrato",
    "periodoValidez",
    "cocumentoReferenciaContrato"
})
public class TipoContrato implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID")
    protected TipoIdentificador id;
    @XmlElement(name = "FechaEmision", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar fechaEmision;
    @XmlElement(name = "HoraEmision", type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "time")
    protected Calendar horaEmision;
    @XmlElement(name = "TipoCodigoContrato")
    protected TipoCodigo tipoCodigoContrato;
    @XmlElement(name = "TipoContrato")
    protected TipoTexto tipoContrato;
    @XmlElement(name = "PeriodoValidez")
    protected TipoPeriodo periodoValidez;
    @XmlElement(name = "CocumentoReferenciaContrato")
    protected List<TipoDocumentoReferencia> cocumentoReferenciaContrato;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the fechaEmision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getFechaEmision() {
        return fechaEmision;
    }

    /**
     * Sets the value of the fechaEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaEmision(Calendar value) {
        this.fechaEmision = value;
    }

    /**
     * Gets the value of the horaEmision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getHoraEmision() {
        return horaEmision;
    }

    /**
     * Sets the value of the horaEmision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraEmision(Calendar value) {
        this.horaEmision = value;
    }

    /**
     * Gets the value of the tipoCodigoContrato property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getTipoCodigoContrato() {
        return tipoCodigoContrato;
    }

    /**
     * Sets the value of the tipoCodigoContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setTipoCodigoContrato(TipoCodigo value) {
        this.tipoCodigoContrato = value;
    }

    /**
     * Gets the value of the tipoContrato property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getTipoContrato() {
        return tipoContrato;
    }

    /**
     * Sets the value of the tipoContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setTipoContrato(TipoTexto value) {
        this.tipoContrato = value;
    }

    /**
     * Gets the value of the periodoValidez property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPeriodo }
     *     
     */
    public TipoPeriodo getPeriodoValidez() {
        return periodoValidez;
    }

    /**
     * Sets the value of the periodoValidez property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPeriodo }
     *     
     */
    public void setPeriodoValidez(TipoPeriodo value) {
        this.periodoValidez = value;
    }

    /**
     * Gets the value of the cocumentoReferenciaContrato property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cocumentoReferenciaContrato property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCocumentoReferenciaContrato().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoDocumentoReferencia }
     * 
     * 
     */
    public List<TipoDocumentoReferencia> getCocumentoReferenciaContrato() {
        if (cocumentoReferenciaContrato == null) {
            cocumentoReferenciaContrato = new ArrayList<TipoDocumentoReferencia>();
        }
        return this.cocumentoReferenciaContrato;
    }

}
