//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoArticulo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoArticulo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Descripcion" type="{http://www.growupit.com/gideEsquema}TipoTexto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CantidadPaquete" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TamanoNumericoPaquete" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="IndicadorCatalogo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndicadorRiesgo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="InformacionAdicional" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="PalabraClave" type="{http://www.growupit.com/gideEsquema}TipoTexto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Marca" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NombreModelo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticulosCompradores" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticuloVendedores" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticuloFabricante" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticuloEstandar" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticuloCatalogo" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" minOccurs="0"/>
 *         &lt;element name="IdentificacionArticuloAdicional" type="{http://www.growupit.com/gideEsquema}TipoIdentificacionArticulos" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DocumentoRefereciaCatalogo" type="{http://www.growupit.com/gideEsquema}TipoDocumentoReferencia" minOccurs="0"/>
 *         &lt;element name="ReferenciaDocumentoEspecificacionArticulo" type="{http://www.growupit.com/gideEsquema}TipoDocumentoReferencia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaisOrigen" type="{http://www.growupit.com/gideEsquema}TipoPais" minOccurs="0"/>
 *         &lt;element name="ClasificacionMercancia" type="{http://www.growupit.com/gideEsquema}TipoClasificacionMercancia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CondicionesTransaccion" type="{http://www.growupit.com/gideEsquema}TipoCondicionesTransaccion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ArticuloPeligroso" type="{http://www.growupit.com/gideEsquema}TipoArticuloPeligroso" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CategoriaImpuestoClasificado" type="{http://www.growupit.com/gideEsquema}TipoCategoriaImpuesto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PropiedadArticuloAdicional" type="{http://www.growupit.com/gideEsquema}TipoPropiedadArticulo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TerceroFabricante" type="{http://www.growupit.com/gideEsquema}TipoTercero" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TerceroProveedorContenidoInformacion" type="{http://www.growupit.com/gideEsquema}TipoTercero" minOccurs="0"/>
 *         &lt;element name="DireccionOriginal" type="{http://www.growupit.com/gideEsquema}TipoDireccion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InstanciaArticulo" type="{http://www.growupit.com/gideEsquema}TipoInstanciaArticulo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoArticulo", propOrder = {
    "descripcion",
    "cantidadPaquete",
    "tamanoNumericoPaquete",
    "indicadorCatalogo",
    "nombre",
    "indicadorRiesgo",
    "informacionAdicional",
    "palabraClave",
    "marca",
    "nombreModelo",
    "identificacionArticulosCompradores",
    "identificacionArticuloVendedores",
    "identificacionArticuloFabricante",
    "identificacionArticuloEstandar",
    "identificacionArticuloCatalogo",
    "identificacionArticuloAdicional",
    "documentoRefereciaCatalogo",
    "referenciaDocumentoEspecificacionArticulo",
    "paisOrigen",
    "clasificacionMercancia",
    "condicionesTransaccion",
    "articuloPeligroso",
    "categoriaImpuestoClasificado",
    "propiedadArticuloAdicional",
    "terceroFabricante",
    "terceroProveedorContenidoInformacion",
    "direccionOriginal",
    "instanciaArticulo"
})
public class TipoArticulo
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "Descripcion")
    protected List<TipoTexto> descripcion;
    @XmlElement(name = "CantidadPaquete")
    protected BigDecimal cantidadPaquete;
    @XmlElement(name = "TamanoNumericoPaquete")
    protected BigDecimal tamanoNumericoPaquete;
    @XmlElement(name = "IndicadorCatalogo")
    protected Boolean indicadorCatalogo;
    @XmlElement(name = "Nombre")
    protected String nombre;
    @XmlElement(name = "IndicadorRiesgo")
    protected Boolean indicadorRiesgo;
    @XmlElement(name = "InformacionAdicional")
    protected TipoTexto informacionAdicional;
    @XmlElement(name = "PalabraClave")
    protected List<TipoTexto> palabraClave;
    @XmlElement(name = "Marca")
    protected List<String> marca;
    @XmlElement(name = "NombreModelo")
    protected List<String> nombreModelo;
    @XmlElement(name = "IdentificacionArticulosCompradores")
    protected TipoIdentificacionArticulos identificacionArticulosCompradores;
    @XmlElement(name = "IdentificacionArticuloVendedores")
    protected TipoIdentificacionArticulos identificacionArticuloVendedores;
    @XmlElement(name = "IdentificacionArticuloFabricante")
    protected List<TipoIdentificacionArticulos> identificacionArticuloFabricante;
    @XmlElement(name = "IdentificacionArticuloEstandar")
    protected TipoIdentificacionArticulos identificacionArticuloEstandar;
    @XmlElement(name = "IdentificacionArticuloCatalogo")
    protected TipoIdentificacionArticulos identificacionArticuloCatalogo;
    @XmlElement(name = "IdentificacionArticuloAdicional")
    protected List<TipoIdentificacionArticulos> identificacionArticuloAdicional;
    @XmlElement(name = "DocumentoRefereciaCatalogo")
    protected TipoDocumentoReferencia documentoRefereciaCatalogo;
    @XmlElement(name = "ReferenciaDocumentoEspecificacionArticulo")
    protected List<TipoDocumentoReferencia> referenciaDocumentoEspecificacionArticulo;
    @XmlElement(name = "PaisOrigen")
    protected TipoPais paisOrigen;
    @XmlElement(name = "ClasificacionMercancia")
    protected List<TipoClasificacionMercancia> clasificacionMercancia;
    @XmlElement(name = "CondicionesTransaccion")
    protected List<TipoCondicionesTransaccion> condicionesTransaccion;
    @XmlElement(name = "ArticuloPeligroso")
    protected List<TipoArticuloPeligroso> articuloPeligroso;
    @XmlElement(name = "CategoriaImpuestoClasificado")
    protected List<TipoCategoriaImpuesto> categoriaImpuestoClasificado;
    @XmlElement(name = "PropiedadArticuloAdicional")
    protected List<TipoPropiedadArticulo> propiedadArticuloAdicional;
    @XmlElement(name = "TerceroFabricante")
    protected List<TipoTercero> terceroFabricante;
    @XmlElement(name = "TerceroProveedorContenidoInformacion")
    protected TipoTercero terceroProveedorContenidoInformacion;
    @XmlElement(name = "DireccionOriginal")
    protected List<TipoDireccion> direccionOriginal;
    @XmlElement(name = "InstanciaArticulo")
    protected List<TipoInstanciaArticulo> instanciaArticulo;

    /**
     * Gets the value of the descripcion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descripcion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescripcion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTexto }
     * 
     * 
     */
    public List<TipoTexto> getDescripcion() {
        if (descripcion == null) {
            descripcion = new ArrayList<TipoTexto>();
        }
        return this.descripcion;
    }

    /**
     * Gets the value of the cantidadPaquete property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCantidadPaquete() {
        return cantidadPaquete;
    }

    /**
     * Sets the value of the cantidadPaquete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCantidadPaquete(BigDecimal value) {
        this.cantidadPaquete = value;
    }

    /**
     * Gets the value of the tamanoNumericoPaquete property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTamanoNumericoPaquete() {
        return tamanoNumericoPaquete;
    }

    /**
     * Sets the value of the tamanoNumericoPaquete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTamanoNumericoPaquete(BigDecimal value) {
        this.tamanoNumericoPaquete = value;
    }

    /**
     * Gets the value of the indicadorCatalogo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorCatalogo() {
        return indicadorCatalogo;
    }

    /**
     * Sets the value of the indicadorCatalogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorCatalogo(Boolean value) {
        this.indicadorCatalogo = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the indicadorRiesgo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorRiesgo() {
        return indicadorRiesgo;
    }

    /**
     * Sets the value of the indicadorRiesgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorRiesgo(Boolean value) {
        this.indicadorRiesgo = value;
    }

    /**
     * Gets the value of the informacionAdicional property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getInformacionAdicional() {
        return informacionAdicional;
    }

    /**
     * Sets the value of the informacionAdicional property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setInformacionAdicional(TipoTexto value) {
        this.informacionAdicional = value;
    }

    /**
     * Gets the value of the palabraClave property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the palabraClave property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPalabraClave().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTexto }
     * 
     * 
     */
    public List<TipoTexto> getPalabraClave() {
        if (palabraClave == null) {
            palabraClave = new ArrayList<TipoTexto>();
        }
        return this.palabraClave;
    }

    /**
     * Gets the value of the marca property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marca property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarca().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMarca() {
        if (marca == null) {
            marca = new ArrayList<String>();
        }
        return this.marca;
    }

    /**
     * Gets the value of the nombreModelo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nombreModelo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNombreModelo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNombreModelo() {
        if (nombreModelo == null) {
            nombreModelo = new ArrayList<String>();
        }
        return this.nombreModelo;
    }

    /**
     * Gets the value of the identificacionArticulosCompradores property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public TipoIdentificacionArticulos getIdentificacionArticulosCompradores() {
        return identificacionArticulosCompradores;
    }

    /**
     * Sets the value of the identificacionArticulosCompradores property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public void setIdentificacionArticulosCompradores(TipoIdentificacionArticulos value) {
        this.identificacionArticulosCompradores = value;
    }

    /**
     * Gets the value of the identificacionArticuloVendedores property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public TipoIdentificacionArticulos getIdentificacionArticuloVendedores() {
        return identificacionArticuloVendedores;
    }

    /**
     * Sets the value of the identificacionArticuloVendedores property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public void setIdentificacionArticuloVendedores(TipoIdentificacionArticulos value) {
        this.identificacionArticuloVendedores = value;
    }

    /**
     * Gets the value of the identificacionArticuloFabricante property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificacionArticuloFabricante property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacionArticuloFabricante().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoIdentificacionArticulos }
     * 
     * 
     */
    public List<TipoIdentificacionArticulos> getIdentificacionArticuloFabricante() {
        if (identificacionArticuloFabricante == null) {
            identificacionArticuloFabricante = new ArrayList<TipoIdentificacionArticulos>();
        }
        return this.identificacionArticuloFabricante;
    }

    /**
     * Gets the value of the identificacionArticuloEstandar property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public TipoIdentificacionArticulos getIdentificacionArticuloEstandar() {
        return identificacionArticuloEstandar;
    }

    /**
     * Sets the value of the identificacionArticuloEstandar property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public void setIdentificacionArticuloEstandar(TipoIdentificacionArticulos value) {
        this.identificacionArticuloEstandar = value;
    }

    /**
     * Gets the value of the identificacionArticuloCatalogo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public TipoIdentificacionArticulos getIdentificacionArticuloCatalogo() {
        return identificacionArticuloCatalogo;
    }

    /**
     * Sets the value of the identificacionArticuloCatalogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificacionArticulos }
     *     
     */
    public void setIdentificacionArticuloCatalogo(TipoIdentificacionArticulos value) {
        this.identificacionArticuloCatalogo = value;
    }

    /**
     * Gets the value of the identificacionArticuloAdicional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificacionArticuloAdicional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacionArticuloAdicional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoIdentificacionArticulos }
     * 
     * 
     */
    public List<TipoIdentificacionArticulos> getIdentificacionArticuloAdicional() {
        if (identificacionArticuloAdicional == null) {
            identificacionArticuloAdicional = new ArrayList<TipoIdentificacionArticulos>();
        }
        return this.identificacionArticuloAdicional;
    }

    /**
     * Gets the value of the documentoRefereciaCatalogo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDocumentoReferencia }
     *     
     */
    public TipoDocumentoReferencia getDocumentoRefereciaCatalogo() {
        return documentoRefereciaCatalogo;
    }

    /**
     * Sets the value of the documentoRefereciaCatalogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDocumentoReferencia }
     *     
     */
    public void setDocumentoRefereciaCatalogo(TipoDocumentoReferencia value) {
        this.documentoRefereciaCatalogo = value;
    }

    /**
     * Gets the value of the referenciaDocumentoEspecificacionArticulo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenciaDocumentoEspecificacionArticulo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenciaDocumentoEspecificacionArticulo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoDocumentoReferencia }
     * 
     * 
     */
    public List<TipoDocumentoReferencia> getReferenciaDocumentoEspecificacionArticulo() {
        if (referenciaDocumentoEspecificacionArticulo == null) {
            referenciaDocumentoEspecificacionArticulo = new ArrayList<TipoDocumentoReferencia>();
        }
        return this.referenciaDocumentoEspecificacionArticulo;
    }

    /**
     * Gets the value of the paisOrigen property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPais }
     *     
     */
    public TipoPais getPaisOrigen() {
        return paisOrigen;
    }

    /**
     * Sets the value of the paisOrigen property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPais }
     *     
     */
    public void setPaisOrigen(TipoPais value) {
        this.paisOrigen = value;
    }

    /**
     * Gets the value of the clasificacionMercancia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clasificacionMercancia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClasificacionMercancia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoClasificacionMercancia }
     * 
     * 
     */
    public List<TipoClasificacionMercancia> getClasificacionMercancia() {
        if (clasificacionMercancia == null) {
            clasificacionMercancia = new ArrayList<TipoClasificacionMercancia>();
        }
        return this.clasificacionMercancia;
    }

    /**
     * Gets the value of the condicionesTransaccion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condicionesTransaccion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondicionesTransaccion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoCondicionesTransaccion }
     * 
     * 
     */
    public List<TipoCondicionesTransaccion> getCondicionesTransaccion() {
        if (condicionesTransaccion == null) {
            condicionesTransaccion = new ArrayList<TipoCondicionesTransaccion>();
        }
        return this.condicionesTransaccion;
    }

    /**
     * Gets the value of the articuloPeligroso property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articuloPeligroso property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticuloPeligroso().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoArticuloPeligroso }
     * 
     * 
     */
    public List<TipoArticuloPeligroso> getArticuloPeligroso() {
        if (articuloPeligroso == null) {
            articuloPeligroso = new ArrayList<TipoArticuloPeligroso>();
        }
        return this.articuloPeligroso;
    }

    /**
     * Gets the value of the categoriaImpuestoClasificado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoriaImpuestoClasificado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoriaImpuestoClasificado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoCategoriaImpuesto }
     * 
     * 
     */
    public List<TipoCategoriaImpuesto> getCategoriaImpuestoClasificado() {
        if (categoriaImpuestoClasificado == null) {
            categoriaImpuestoClasificado = new ArrayList<TipoCategoriaImpuesto>();
        }
        return this.categoriaImpuestoClasificado;
    }

    /**
     * Gets the value of the propiedadArticuloAdicional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the propiedadArticuloAdicional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropiedadArticuloAdicional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoPropiedadArticulo }
     * 
     * 
     */
    public List<TipoPropiedadArticulo> getPropiedadArticuloAdicional() {
        if (propiedadArticuloAdicional == null) {
            propiedadArticuloAdicional = new ArrayList<TipoPropiedadArticulo>();
        }
        return this.propiedadArticuloAdicional;
    }

    /**
     * Gets the value of the terceroFabricante property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the terceroFabricante property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTerceroFabricante().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTercero }
     * 
     * 
     */
    public List<TipoTercero> getTerceroFabricante() {
        if (terceroFabricante == null) {
            terceroFabricante = new ArrayList<TipoTercero>();
        }
        return this.terceroFabricante;
    }

    /**
     * Gets the value of the terceroProveedorContenidoInformacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTercero }
     *     
     */
    public TipoTercero getTerceroProveedorContenidoInformacion() {
        return terceroProveedorContenidoInformacion;
    }

    /**
     * Sets the value of the terceroProveedorContenidoInformacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTercero }
     *     
     */
    public void setTerceroProveedorContenidoInformacion(TipoTercero value) {
        this.terceroProveedorContenidoInformacion = value;
    }

    /**
     * Gets the value of the direccionOriginal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the direccionOriginal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDireccionOriginal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoDireccion }
     * 
     * 
     */
    public List<TipoDireccion> getDireccionOriginal() {
        if (direccionOriginal == null) {
            direccionOriginal = new ArrayList<TipoDireccion>();
        }
        return this.direccionOriginal;
    }

    /**
     * Gets the value of the instanciaArticulo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanciaArticulo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanciaArticulo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoInstanciaArticulo }
     * 
     * 
     */
    public List<TipoInstanciaArticulo> getInstanciaArticulo() {
        if (instanciaArticulo == null) {
            instanciaArticulo = new ArrayList<TipoInstanciaArticulo>();
        }
        return this.instanciaArticulo;
    }

}
