//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter2;


/**
 * <p>Java class for TipoDetalleFactura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoDetalleFactura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador"/>
 *         &lt;element name="UUID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="Nota" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="CantidadFactura" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="MontoLineaExtension" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="FechaImpuesto" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CodigoCosteContable" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="CostoContable" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="IndicadorSinCargo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ReferenciaLineaPedido" type="{http://www.growupit.com/gideEsquema}TipoReferenciaLineaPedido" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LineaReferenciaEnvio" type="{http://www.growupit.com/gideEsquema}TipoLineaReferencia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReferenciaLineaRecepcion" type="{http://www.growupit.com/gideEsquema}TipoLineaReferencia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReferenciaFactura" type="{http://www.growupit.com/gideEsquema}TipoReferenciaFactura" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReferenciaDocumento" type="{http://www.growupit.com/gideEsquema}TipoDocumentoReferencia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReferenciaPrecios" type="{http://www.growupit.com/gideEsquema}TipoReferenciaPrecios" minOccurs="0"/>
 *         &lt;element name="PartidoOriginador" type="{http://www.growupit.com/gideEsquema}TipoTercero" minOccurs="0"/>
 *         &lt;element name="Entrega" type="{http://www.growupit.com/gideEsquema}TipoEntrega" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CondicionesPago" type="{http://www.growupit.com/gideEsquema}TipoTerminosPago" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Cargo" type="{http://www.growupit.com/gideEsquema}TipoCargo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ImpuestoTotal" type="{http://www.growupit.com/gideEsquema}TipoImpuestoTotal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Articulo" type="{http://www.growupit.com/gideEsquema}TipoArticulo"/>
 *         &lt;element name="Precio" type="{http://www.growupit.com/gideEsquema}TipoPrecio"/>
 *         &lt;element name="TerminosEntrega" type="{http://www.growupit.com/gideEsquema}TipoTerminosEntrega" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoDetalleFactura", propOrder = {
    "id",
    "uuid",
    "nota",
    "cantidadFactura",
    "montoLineaExtension",
    "fechaImpuesto",
    "codigoCosteContable",
    "costoContable",
    "indicadorSinCargo",
    "referenciaLineaPedido",
    "lineaReferenciaEnvio",
    "referenciaLineaRecepcion",
    "referenciaFactura",
    "referenciaDocumento",
    "referenciaPrecios",
    "partidoOriginador",
    "entrega",
    "condicionesPago",
    "cargo",
    "impuestoTotal",
    "articulo",
    "precio",
    "terminosEntrega"
})
public class TipoDetalleFactura
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID", required = true)
    protected TipoIdentificador id;
    @XmlElement(name = "UUID")
    protected TipoIdentificador uuid;
    @XmlElement(name = "Nota")
    protected TipoTexto nota;
    @XmlElement(name = "CantidadFactura", required = true)
    protected BigDecimal cantidadFactura;
    @XmlElement(name = "MontoLineaExtension", required = true)
    protected BigDecimal montoLineaExtension;
    @XmlElement(name = "FechaImpuesto", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar fechaImpuesto;
    @XmlElement(name = "CodigoCosteContable")
    protected TipoCodigo codigoCosteContable;
    @XmlElement(name = "CostoContable")
    protected TipoTexto costoContable;
    @XmlElement(name = "IndicadorSinCargo")
    protected Boolean indicadorSinCargo;
    @XmlElement(name = "ReferenciaLineaPedido")
    protected List<TipoReferenciaLineaPedido> referenciaLineaPedido;
    @XmlElement(name = "LineaReferenciaEnvio")
    protected List<TipoLineaReferencia> lineaReferenciaEnvio;
    @XmlElement(name = "ReferenciaLineaRecepcion")
    protected List<TipoLineaReferencia> referenciaLineaRecepcion;
    @XmlElement(name = "ReferenciaFactura")
    protected List<TipoReferenciaFactura> referenciaFactura;
    @XmlElement(name = "ReferenciaDocumento")
    protected List<TipoDocumentoReferencia> referenciaDocumento;
    @XmlElement(name = "ReferenciaPrecios")
    protected TipoReferenciaPrecios referenciaPrecios;
    @XmlElement(name = "PartidoOriginador")
    protected TipoTercero partidoOriginador;
    @XmlElement(name = "Entrega")
    protected List<TipoEntrega> entrega;
    @XmlElement(name = "CondicionesPago")
    protected List<TipoTerminosPago> condicionesPago;
    @XmlElement(name = "Cargo")
    protected List<TipoCargo> cargo;
    @XmlElement(name = "ImpuestoTotal")
    protected List<TipoImpuestoTotal> impuestoTotal;
    @XmlElement(name = "Articulo", required = true)
    protected TipoArticulo articulo;
    @XmlElement(name = "Precio", required = true)
    protected TipoPrecio precio;
    @XmlElement(name = "TerminosEntrega")
    protected TipoTerminosEntrega terminosEntrega;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setUUID(TipoIdentificador value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the nota property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getNota() {
        return nota;
    }

    /**
     * Sets the value of the nota property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setNota(TipoTexto value) {
        this.nota = value;
    }

    /**
     * Gets the value of the cantidadFactura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCantidadFactura() {
        return cantidadFactura;
    }

    /**
     * Sets the value of the cantidadFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCantidadFactura(BigDecimal value) {
        this.cantidadFactura = value;
    }

    /**
     * Gets the value of the montoLineaExtension property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoLineaExtension() {
        return montoLineaExtension;
    }

    /**
     * Sets the value of the montoLineaExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoLineaExtension(BigDecimal value) {
        this.montoLineaExtension = value;
    }

    /**
     * Gets the value of the fechaImpuesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getFechaImpuesto() {
        return fechaImpuesto;
    }

    /**
     * Sets the value of the fechaImpuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaImpuesto(Calendar value) {
        this.fechaImpuesto = value;
    }

    /**
     * Gets the value of the codigoCosteContable property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoCosteContable() {
        return codigoCosteContable;
    }

    /**
     * Sets the value of the codigoCosteContable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoCosteContable(TipoCodigo value) {
        this.codigoCosteContable = value;
    }

    /**
     * Gets the value of the costoContable property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getCostoContable() {
        return costoContable;
    }

    /**
     * Sets the value of the costoContable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setCostoContable(TipoTexto value) {
        this.costoContable = value;
    }

    /**
     * Gets the value of the indicadorSinCargo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorSinCargo() {
        return indicadorSinCargo;
    }

    /**
     * Sets the value of the indicadorSinCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorSinCargo(Boolean value) {
        this.indicadorSinCargo = value;
    }

    /**
     * Gets the value of the referenciaLineaPedido property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenciaLineaPedido property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenciaLineaPedido().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoReferenciaLineaPedido }
     * 
     * 
     */
    public List<TipoReferenciaLineaPedido> getReferenciaLineaPedido() {
        if (referenciaLineaPedido == null) {
            referenciaLineaPedido = new ArrayList<TipoReferenciaLineaPedido>();
        }
        return this.referenciaLineaPedido;
    }

    /**
     * Gets the value of the lineaReferenciaEnvio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineaReferenciaEnvio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineaReferenciaEnvio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoLineaReferencia }
     * 
     * 
     */
    public List<TipoLineaReferencia> getLineaReferenciaEnvio() {
        if (lineaReferenciaEnvio == null) {
            lineaReferenciaEnvio = new ArrayList<TipoLineaReferencia>();
        }
        return this.lineaReferenciaEnvio;
    }

    /**
     * Gets the value of the referenciaLineaRecepcion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenciaLineaRecepcion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenciaLineaRecepcion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoLineaReferencia }
     * 
     * 
     */
    public List<TipoLineaReferencia> getReferenciaLineaRecepcion() {
        if (referenciaLineaRecepcion == null) {
            referenciaLineaRecepcion = new ArrayList<TipoLineaReferencia>();
        }
        return this.referenciaLineaRecepcion;
    }

    /**
     * Gets the value of the referenciaFactura property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenciaFactura property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenciaFactura().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoReferenciaFactura }
     * 
     * 
     */
    public List<TipoReferenciaFactura> getReferenciaFactura() {
        if (referenciaFactura == null) {
            referenciaFactura = new ArrayList<TipoReferenciaFactura>();
        }
        return this.referenciaFactura;
    }

    /**
     * Gets the value of the referenciaDocumento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referenciaDocumento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferenciaDocumento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoDocumentoReferencia }
     * 
     * 
     */
    public List<TipoDocumentoReferencia> getReferenciaDocumento() {
        if (referenciaDocumento == null) {
            referenciaDocumento = new ArrayList<TipoDocumentoReferencia>();
        }
        return this.referenciaDocumento;
    }

    /**
     * Gets the value of the referenciaPrecios property.
     * 
     * @return
     *     possible object is
     *     {@link TipoReferenciaPrecios }
     *     
     */
    public TipoReferenciaPrecios getReferenciaPrecios() {
        return referenciaPrecios;
    }

    /**
     * Sets the value of the referenciaPrecios property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoReferenciaPrecios }
     *     
     */
    public void setReferenciaPrecios(TipoReferenciaPrecios value) {
        this.referenciaPrecios = value;
    }

    /**
     * Gets the value of the partidoOriginador property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTercero }
     *     
     */
    public TipoTercero getPartidoOriginador() {
        return partidoOriginador;
    }

    /**
     * Sets the value of the partidoOriginador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTercero }
     *     
     */
    public void setPartidoOriginador(TipoTercero value) {
        this.partidoOriginador = value;
    }

    /**
     * Gets the value of the entrega property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entrega property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntrega().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoEntrega }
     * 
     * 
     */
    public List<TipoEntrega> getEntrega() {
        if (entrega == null) {
            entrega = new ArrayList<TipoEntrega>();
        }
        return this.entrega;
    }

    /**
     * Gets the value of the condicionesPago property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condicionesPago property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondicionesPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTerminosPago }
     * 
     * 
     */
    public List<TipoTerminosPago> getCondicionesPago() {
        if (condicionesPago == null) {
            condicionesPago = new ArrayList<TipoTerminosPago>();
        }
        return this.condicionesPago;
    }

    /**
     * Gets the value of the cargo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cargo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCargo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoCargo }
     * 
     * 
     */
    public List<TipoCargo> getCargo() {
        if (cargo == null) {
            cargo = new ArrayList<TipoCargo>();
        }
        return this.cargo;
    }

    /**
     * Gets the value of the impuestoTotal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the impuestoTotal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImpuestoTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoImpuestoTotal }
     * 
     * 
     */
    public List<TipoImpuestoTotal> getImpuestoTotal() {
        if (impuestoTotal == null) {
            impuestoTotal = new ArrayList<TipoImpuestoTotal>();
        }
        return this.impuestoTotal;
    }

    /**
     * Gets the value of the articulo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoArticulo }
     *     
     */
    public TipoArticulo getArticulo() {
        return articulo;
    }

    /**
     * Sets the value of the articulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoArticulo }
     *     
     */
    public void setArticulo(TipoArticulo value) {
        this.articulo = value;
    }

    /**
     * Gets the value of the precio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoPrecio }
     *     
     */
    public TipoPrecio getPrecio() {
        return precio;
    }

    /**
     * Sets the value of the precio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoPrecio }
     *     
     */
    public void setPrecio(TipoPrecio value) {
        this.precio = value;
    }

    /**
     * Gets the value of the terminosEntrega property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTerminosEntrega }
     *     
     */
    public TipoTerminosEntrega getTerminosEntrega() {
        return terminosEntrega;
    }

    /**
     * Sets the value of the terminosEntrega property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTerminosEntrega }
     *     
     */
    public void setTerminosEntrega(TipoTerminosEntrega value) {
        this.terminosEntrega = value;
    }

}
