//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3._2001.xmlschema.Adapter2;
import org.w3._2001.xmlschema.Adapter3;


/**
 * <p>Java class for TipoReferenciaPedido complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoReferenciaPedido">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador"/>
 *         &lt;element name="IdOrdenesVenta" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="IndicadorCopia" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UUID" type="{http://www.growupit.com/gideEsquema}TipoIdentificador" minOccurs="0"/>
 *         &lt;element name="FechaAsunto" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="HoraAsunto" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="ReferenciaCliente" type="{http://www.growupit.com/gideEsquema}TipoTexto" minOccurs="0"/>
 *         &lt;element name="Documentoreferencia" type="{http://www.growupit.com/gideEsquema}TipoDocumentoReferencia" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoReferenciaPedido", propOrder = {
    "id",
    "idOrdenesVenta",
    "indicadorCopia",
    "uuid",
    "fechaAsunto",
    "horaAsunto",
    "referenciaCliente",
    "documentoreferencia"
})
public class TipoReferenciaPedido
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "ID", required = true)
    protected TipoIdentificador id;
    @XmlElement(name = "IdOrdenesVenta")
    protected TipoIdentificador idOrdenesVenta;
    @XmlElement(name = "IndicadorCopia")
    protected Boolean indicadorCopia;
    @XmlElement(name = "UUID")
    protected TipoIdentificador uuid;
    @XmlElement(name = "FechaAsunto", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar fechaAsunto;
    @XmlElement(name = "HoraAsunto", type = String.class)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "time")
    protected Calendar horaAsunto;
    @XmlElement(name = "ReferenciaCliente")
    protected TipoTexto referenciaCliente;
    @XmlElement(name = "Documentoreferencia")
    protected TipoDocumentoReferencia documentoreferencia;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setID(TipoIdentificador value) {
        this.id = value;
    }

    /**
     * Gets the value of the idOrdenesVenta property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getIdOrdenesVenta() {
        return idOrdenesVenta;
    }

    /**
     * Sets the value of the idOrdenesVenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setIdOrdenesVenta(TipoIdentificador value) {
        this.idOrdenesVenta = value;
    }

    /**
     * Gets the value of the indicadorCopia property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIndicadorCopia() {
        return indicadorCopia;
    }

    /**
     * Sets the value of the indicadorCopia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIndicadorCopia(Boolean value) {
        this.indicadorCopia = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setUUID(TipoIdentificador value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the fechaAsunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getFechaAsunto() {
        return fechaAsunto;
    }

    /**
     * Sets the value of the fechaAsunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaAsunto(Calendar value) {
        this.fechaAsunto = value;
    }

    /**
     * Gets the value of the horaAsunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getHoraAsunto() {
        return horaAsunto;
    }

    /**
     * Sets the value of the horaAsunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoraAsunto(Calendar value) {
        this.horaAsunto = value;
    }

    /**
     * Gets the value of the referenciaCliente property.
     * 
     * @return
     *     possible object is
     *     {@link TipoTexto }
     *     
     */
    public TipoTexto getReferenciaCliente() {
        return referenciaCliente;
    }

    /**
     * Sets the value of the referenciaCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoTexto }
     *     
     */
    public void setReferenciaCliente(TipoTexto value) {
        this.referenciaCliente = value;
    }

    /**
     * Gets the value of the documentoreferencia property.
     * 
     * @return
     *     possible object is
     *     {@link TipoDocumentoReferencia }
     *     
     */
    public TipoDocumentoReferencia getDocumentoreferencia() {
        return documentoreferencia;
    }

    /**
     * Sets the value of the documentoreferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoDocumentoReferencia }
     *     
     */
    public void setDocumentoreferencia(TipoDocumentoReferencia value) {
        this.documentoreferencia = value;
    }

}
