//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:57:14 AM CDT 
//


package com.growupit.gideesquema;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoAtriburoFisico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoAtriburoFisico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDAtriburo" type="{http://www.growupit.com/gideEsquema}TipoIdentificador"/>
 *         &lt;element name="CodigoPosision" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="CodigoDescripcion" type="{http://www.growupit.com/gideEsquema}TipoCodigo" minOccurs="0"/>
 *         &lt;element name="Descripcion" type="{http://www.growupit.com/gideEsquema}TipoTexto" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoAtriburoFisico", propOrder = {
    "idAtriburo",
    "codigoPosision",
    "codigoDescripcion",
    "descripcion"
})
public class TipoAtriburoFisico
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "IDAtriburo", required = true)
    protected TipoIdentificador idAtriburo;
    @XmlElement(name = "CodigoPosision")
    protected TipoCodigo codigoPosision;
    @XmlElement(name = "CodigoDescripcion")
    protected TipoCodigo codigoDescripcion;
    @XmlElement(name = "Descripcion")
    protected List<TipoTexto> descripcion;

    /**
     * Gets the value of the idAtriburo property.
     * 
     * @return
     *     possible object is
     *     {@link TipoIdentificador }
     *     
     */
    public TipoIdentificador getIDAtriburo() {
        return idAtriburo;
    }

    /**
     * Sets the value of the idAtriburo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoIdentificador }
     *     
     */
    public void setIDAtriburo(TipoIdentificador value) {
        this.idAtriburo = value;
    }

    /**
     * Gets the value of the codigoPosision property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoPosision() {
        return codigoPosision;
    }

    /**
     * Sets the value of the codigoPosision property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoPosision(TipoCodigo value) {
        this.codigoPosision = value;
    }

    /**
     * Gets the value of the codigoDescripcion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCodigo }
     *     
     */
    public TipoCodigo getCodigoDescripcion() {
        return codigoDescripcion;
    }

    /**
     * Sets the value of the codigoDescripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCodigo }
     *     
     */
    public void setCodigoDescripcion(TipoCodigo value) {
        this.codigoDescripcion = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descripcion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescripcion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoTexto }
     * 
     * 
     */
    public List<TipoTexto> getDescripcion() {
        if (descripcion == null) {
            descripcion = new ArrayList<TipoTexto>();
        }
        return this.descripcion;
    }

}
