//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.27 at 09:36:21 AM CDT 
//


package co.gov.dian.contratos.facturaelectronica.v1.structures;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import un.unece.uncefact.data.specification.unqualifieddatatypesschemamodule._2.AmountType;


/**
 * <p>Java class for AdditionalMonetaryTotal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalMonetaryTotal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RepercussionsTotalTaxAmount" type="{urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2}AmountType" minOccurs="0"/>
 *         &lt;element name="RetainTotalTaxAmount" type="{urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2}AmountType" minOccurs="0"/>
 *         &lt;element name="InvoiceTotalLocalCurrencyAmount" type="{urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2}AmountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalMonetaryTotal", propOrder = {
    "repercussionsTotalTaxAmount",
    "retainTotalTaxAmount",
    "invoiceTotalLocalCurrencyAmount"
})
public class AdditionalMonetaryTotal
    implements Serializable
{

    private final static long serialVersionUID = 123456789012L;
    @XmlElement(name = "RepercussionsTotalTaxAmount")
    protected AmountType repercussionsTotalTaxAmount;
    @XmlElement(name = "RetainTotalTaxAmount")
    protected AmountType retainTotalTaxAmount;
    @XmlElement(name = "InvoiceTotalLocalCurrencyAmount")
    protected AmountType invoiceTotalLocalCurrencyAmount;

    /**
     * Gets the value of the repercussionsTotalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getRepercussionsTotalTaxAmount() {
        return repercussionsTotalTaxAmount;
    }

    /**
     * Sets the value of the repercussionsTotalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setRepercussionsTotalTaxAmount(AmountType value) {
        this.repercussionsTotalTaxAmount = value;
    }

    /**
     * Gets the value of the retainTotalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getRetainTotalTaxAmount() {
        return retainTotalTaxAmount;
    }

    /**
     * Sets the value of the retainTotalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setRetainTotalTaxAmount(AmountType value) {
        this.retainTotalTaxAmount = value;
    }

    /**
     * Gets the value of the invoiceTotalLocalCurrencyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getInvoiceTotalLocalCurrencyAmount() {
        return invoiceTotalLocalCurrencyAmount;
    }

    /**
     * Sets the value of the invoiceTotalLocalCurrencyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setInvoiceTotalLocalCurrencyAmount(AmountType value) {
        this.invoiceTotalLocalCurrencyAmount = value;
    }

}
